# Generated by Django 4.2.3 on 2023-07-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBTest',
            fields=[
                ('test', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
